apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hellworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs_hellworld
  template:
    metadata:
      labels:
        app: nodejs_hellworld
    spec:
      containers:
      - name: nodejs-hellworld
        image: apaixao/nodejs_hellworld:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3096