apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld
spec:
  selector:
    app: nodejs-helloworld
  ports:
    - protocol: TCP
      port: 3096
      targetPort: 3096
  type: LoadBalancer    