apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
      - name: hellokube
        image: hellokube
        imagePullPolicy: Never
        ports:
        - containerPort: 3095